### ISSUE TITLE
How would I check a list of words

### ISSUE THREAD

**Issue by rboothneu** [newton-li/GIS6345#1]
https://github.com/newton-li/GIS6345/blob/9bca549d1849143f3474bd35203a5d41eb195f68/palindrome.py#L18

@newton-li - Another feature of GitHub is that I can submit issues to your repo, calling out specific lines of code (or just describing a problem, or something to work on), and submit it. Then you can make commits that address it (or not) and then close it. This is a great way to collaborate and track changes.

For example, I could ask you to change the code to check through this list:
checkwords = ['bob','sandy','apple','kayak','elephant','racecar']

How would you check each of these and determine if it is a palindrome?

**Comment by newton-li** [comment]
@rboothneu 
I created a new branch and performed a pull request to change the code in the palindrome.py file to test if the list of words. Is this the correct approach to take in this instance? I'm not sure that this is the approach I should have taken because I can't figure out how to open the code in Editor to check this without just copying and pasting, or downloading the entirety of my folder.

**Comment by rboothneu** [comment]
@newton-li - you can set up GitHub Desktop (https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/installing-github-desktop) so that it watches a particular local folder for your repo. Then you can make a new branch, make changes in that folder, and GitHub tracks them there. Commit those changes, verify that they work, and merge that branch with the changes into main.

https://guides.github.com/introduction/flow/
